name: Update Binance Prices

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch and Format Prices
        run: |
          TIMESTAMP=$(date -u +"Updated at %Y-%m-%d %H:%M:%S UTC")
          curl -s https://fapi.binance.com/fapi/v1/ticker/price \
            | jq 'map(select(.symbol | test("BONKUSDT|HBARUSDT|BTCUSDT|OPUSDT|SOLUSDT|SEIUSDT|RNDRUSDT|PEPEUSDT"))) 
            | map({(.symbol): (.price | tonumber)}) 
            | add' > binance-prices.json

          echo "// $TIMESTAMP" >> binance-prices.json

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add binance-prices.json
          git commit -m "Auto-update Binance prices" || echo "No changes"
          git push
