name: Update Binance Prices

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch and Write Prices
        run: |
          curl -s https://fapi.binance.com/fapi/v1/ticker/price > full.json

          jq 'reduce fromjson[] as $item ({}; 
              if $item.symbol == "BONKUSDT" or
                 $item.symbol == "HBARUSDT" or
                 $item.symbol == "BTCUSDT" or
                 $item.symbol == "OPUSDT" or
                 $item.symbol == "SOLUSDT" or
                 $item.symbol == "SEIUSDT" or
                 $item.symbol == "RNDRUSDT" or
                 $item.symbol == "PEPEUSDT" 
              then . + { ($item.symbol): ($item.price | tonumber) } 
              else . end)' full.json > binance-prices.json

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add binance-prices.json
          git commit -m "Auto-update Binance prices: $(date -u)" || echo "No changes"
          git push
